<?php
/**
 * @file
 * Performance Stats module.
 *
 * The Performance Stats module reports the memory-usage of APC and Redis,
 * allowing them to be effectively tuned.
 */


/**
 * Implements hook_hook_info().
 */
function performance_stats_hook_info() {
  $hooks['performance_stats'] = array(
    'group' => 'performance_stats',
  );
  return $hooks;
}

/**
 * Implements hook_menu().
 */
function performance_stats_menu() {
  $items = array();
  $items['admin/reports/performance_stats'] = array(
    'title' => 'Performance stats',
    'page callback' => 'performance_stats_page',
    'access arguments' => array('administer site configuration'),
    'description' => 'View APC and Redis memory-usage information.',
  );
  return $items;
}

/**
 * Page callback for the reports page.
 */
function performance_stats_page() {
  drupal_add_css(drupal_get_path('module', 'performance_stats') . '/performance_stats.css');
  drupal_add_js("https://www.google.com/jsapi", array("external" => TRUE));
  drupal_add_js(drupal_get_path('module', 'performance_stats') . '/performance_stats.js', array('cache' => FALSE));

  // All stats displayed on the page are provided through implementations of
  // hook_performance_stats().
  $stats = module_invoke_all('performance_stats');
  $setting = array(
    'performance_stats' => $stats,
  );
  drupal_add_js($setting, 'setting');

  // Provide an empty div to be populated by JavaScsript.
  $output = '<div id="charts"></div>';
  return $output;
}
